#!/bin/sh

set -e
if [ "$1" = "" ]; then
  echo "Usage: $0 path/to/foo.db"
  echo
  echo "Dump the sqlite3 database file to generic SQL statements."
  exit 1
fi

echo .dump | sqlite3 "$1" | \
	perl -pE 's/PRAGMA foreign_keys=OFF;//; s/^CREATE TABLE /CREATE TABLE IF NOT EXISTS /; s/BEGIN TRANSACTION/BEGIN/g' | \
  sed 's/^);/);\n/g' | \
  sed -z 's/;\nINSERT INTO competition VALUES/,/g' | \
  sed -z 's/;\nINSERT INTO player VALUES/,/g' | \
  sed -z 's/;\nINSERT INTO player_score VALUES/,/g'# | \
  # sed 's/BEGIN;//g' | \
  # sed 's/COMMIT;//g' | \
  # sed -z 's/CREATE TABLE IF NOT EXISTS.+?\n\);//g'

# for ((i = 0; i<140; i++)); do ./sqlite3-to-sql ../../initial_data/$i.db > ../../initial_data/$i.sql; echo $i; done
# で実行した

# ----------------------

# cat *.sql > all.sql
# 以下をall.sqlに先頭に追加
# ```
# SET autocommit=0;
# SET unique_checks=0;
# SET foreign_key_checks=0;
# ```
# 以下をall.sqlを末尾に追加
# ```
# SET autocommit=0;
# SET unique_checks=0;
# SET foreign_key_checks=0;
# ```
